### ISSUE TITLE
Editor without theme throws error

### ISSUE THREAD

**Issue by ivopashov** [spohlenz/tinymce-rails#228]
Editors without a theme (no theme object) throw the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined
    at getImplementation (tinymce.self-ea002509455c2d4e12e195ec050ff03ce90bbe0bdf22bb0d4180bba730c2bcc6.js?body=1:25422)
    at reposition (tinymce.self-ea002509455c2d4e12e195ec050ff03ce90bbe0bdf22bb0d4180bba730c2bcc6.js?body=1:25434)
    at <anonymous>
```

Saw the same issue with the original [tinymce](https://github.com/tinymce/tinymce) repo - [link](https://github.com/tinymce/tinymce/issues/3947). What is more according to docs default theme should be modern so i don't understand why this lack of theme causes trouble.

**Comment by sintro** [comment]
There are also noted, that the problem fixed in latest version (4.7.1 probably). When will the gem be updated to this version?

**Comment by spohlenz** [comment]
The releases for 4.7.1 (and 4.7.0) have now been pushed to RubyGems.org.

**Comment by joelsamuelk** [comment]
I am still experiencing this issue with WordPress 4.9 

tinymce.min.js?ver=4607-20171116:28 Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined
    at h (tinymce.min.js?ver=4607-20171116:28)
    at k (tinymce.min.js?ver=4607-20171116:28)
    at <anonymous>

**Comment by spohlenz** [comment]
@joelsamuelk This issue tracker is for the Rails integration of TinyMCE. You might be looking for https://core.trac.wordpress.org/.

**Comment by joelsamuelk** [comment]
Thank you, I have logged a ticket. 

Regards, 

Joel Kapepula | Developer 3 Woodlands Rd, Woodstock, 7925, Cape Town T: (+27) 21 201 1180 | M: (+27) 72 552 7233 E: joel@responsive.co.za ( andrew@responsive.co.za ) W: responsive.co.za ( http://responsive.co.za/ )
